services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 8080:80/tcp
    environment:
      PIHOLE_UID: 1027
      PIHOLE_GID: 65536
      TZ: 'Europe/Istanbul'
      CUSTOM_CACHE_SIZE: 0
      DNSMASQ_LISTENING: local
      PIHOLE_DNS_: '172.30.0.2'
      FTLCONF_ANALYZE_ONLY_A_AND_AAAA: true
      FTLCONF_MAXDBDAYS: 90
    volumes:
      - '/volume1/docker/pihole/pihole:/etc/pihole'
      - '/volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d'
    networks:
      internal:
        ipv4_address: 172.30.0.3
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    container_name: unbound
    image: "mvance/unbound:latest"
    volumes:
      - '/volume1/docker/unbound:/opt/unbound/etc/unbound/'
    networks:
      internal:
        ipv4_address: 172.30.0.2
    restart: unless-stopped

networks:
  internal:
    ipam:
      config:
        - subnet: 172.30.0.0/29
          gateway: 172.30.0.1

