services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/Istanbul
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/data/media/movies:/movies
      - /volume1/data/downloads:/downloads
    ports:
      - 7878:7878
    network_mode: synobridge
    restart: unless-stopped

