services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    network_mode: synobridge
    ports:
      - 6090:8080/tcp # webapp
      - 8086:8086/tcp # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /volume1/docker/scrutiny:/opt/scrutiny/config
      - /volume1/docker/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sata1"
      - "/dev/sata2"
    environment:
      - COLLECTOR_CRON_SCHEDULE=0 5 * * *
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
